### ISSUE TITLE
Not supported in Sketch 60?

### ISSUE THREAD

**Issue by ziyafenn** [pratikjshah/Sketch-Guides#19]
I'm missing the feature to create guides for a selected layer! This would be amazing addition to my workflow, but seems to be it is not supported anymore?

**Comment by pratikjshah** [comment]
Hi @ziyafenn, Sketch Guides does work for any selected layer (shape, text, group, slice) in Sketch 60. 

Can you please describe what's the error/issue you are facing?

**Comment by ziyafenn** [comment]
Hey, nope, it doesn't work for me. 

I select a group or layer or symbol, run the plugin. it goes to loading state for minute after what nothing is being added.

Thanks in advance.

**Comment by pratikjshah** [comment]
Hi Ziya,

It's strange that you are facing an issue with Sketch Guides. To help me
debug the problem can you please tell me which version of the plugin and
Sketch you are using? A small screen recording would help.

I have personally tested the plugin in Sketch 60 and it is working fine.
Please see the attached video.

Kindly provide more information so I can resolve the issue.
Thank you for reaching out.

--
Pratik Shah
(+ 91 8905750744)
PratikShah.Website <http://pratikshah.website>

**Comment by ziyafenn** [comment]
Yeah, it is strange, i disable and re-enabled the plugin. Now seems to be working. Sorry for confusion, i will reopen the issue if i will face problems with the layer types. 

Thanks a lot.
