### ISSUE TITLE
Stopped working in Sketch 63

### ISSUE THREAD

**Issue by Niknam** [pratikjshah/Sketch-Guides#20]
This plugin seems to not work anymore in Sketch 63. Is it possible to look in to? I use it almost every day. 🙏

Many thanks in advance!

**Comment by pratikjshah** [comment]
Thank you for reaching out, I am working on Mac Cataline and Sketch 62+ issues. I will rollout the update shortly.
Thanks again for reaching out.

**Comment by pratikjshah** [comment]
Hi @Niknam ,

The plugin has been updated to work with Sketch 62+/

**Comment by Niknam** [comment]
Excellent, thank you!
